export default [
  {
    display: "Primary color",
    action: "delete",
    indexPosition: 0,
    price_vary: false,
    qty_vary: false,
    isSelected: false,
    isCustom: false,
    hasSaved: false,

    structure: {
      right: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Yellow", price: 0, qty: 0 },
          { id: 1, name: "White", price: 0, qty: 0 },
          { id: 2, name: "Silver", price: 0, qty: 0 },
          { id: 3, name: "Rose gold", price: 0, qty: 0 },
          { id: 4, name: "Red", price: 0, qty: 0 },
          { id: 5, name: "Rainbow", price: 0, qty: 0 },
          { id: 6, name: "Purple", price: 0, qty: 0 },
          { id: 7, name: "Pink", price: 0, qty: 0 },
          { id: 8, name: "Orange", price: 0, qty: 0 },
          { id: 9, name: "Green", price: 0, qty: 0 },
          { id: 10, name: "Gray", price: 0, qty: 0 },
          { id: 11, name: "Gold", price: 0, qty: 0 },
          { id: 12, name: "Copper", price: 0, qty: 0 },
          { id: 13, name: "Clear", price: 0, qty: 0 },
          { id: 14, name: "Brown", price: 0, qty: 0 },
          { id: 15, name: "Bronze", price: 0, qty: 0 },
          { id: 16, name: "Blue", price: 0, qty: 0 },
          { id: 17, name: "Black", price: 0, qty: 0 },
          { id: 18, name: "Beige", price: 0, qty: 0 },
        ],
        inputValue: "",
        textComponentIsVisible: false,
        bottom: "inputText",
        hasError: true,
        options: [],
      },
    },
    value: 1,
  },
  {
    display: "Secondary color",
    action: "delete",
    indexPosition: 1,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Yellow", price: 0, qty: 0 },
          { id: 1, name: "White", price: 0, qty: 0 },
          { id: 2, name: "Silver", price: 0, qty: 0 },
          { id: 3, name: "Rose gold", price: 0, qty: 0 },
          { id: 4, name: "Red", price: 0, qty: 0 },
          { id: 5, name: "Rainbow", price: 0, qty: 0 },
          { id: 6, name: "Purple", price: 0, qty: 0 },
          { id: 7, name: "Pink", price: 0, qty: 0 },
          { id: 8, name: "Orange", price: 0, qty: 0 },
          { id: 9, name: "Green", price: 0, qty: 0 },
          { id: 10, name: "Gray", price: 0, qty: 0 },
          { id: 11, name: "Gold", price: 0, qty: 0 },
          { id: 12, name: "Copper", price: 0, qty: 0 },
          { id: 13, name: "Clear", price: 0, qty: 0 },
          { id: 14, name: "Brown", price: 0, qty: 0 },
          { id: 15, name: "Bronze", price: 0, qty: 0 },
          { id: 16, name: "Blue", price: 0, qty: 0 },
          { id: 17, name: "Black", price: 0, qty: 0 },
          { id: 18, name: "Beige", price: 0, qty: 0 },
        ],
        inputValue: "",
        textComponentIsVisible: false,
        bottom: "inputText",
        hasError: true,
        options: [],
      },
    },
    value: 2,
  },
  {
    display: "Diameter",
    action: "edit_delete",
    editIsVisible: false,
    indexPosition: 2,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      left: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Inches", isSelected: false, price: 0, qty: 0 },
          { id: 1, name: "Centimeters", isSelected: false, price: 0, qty: 0 },
          { id: 2, name: "Other", isSelected: false, price: 0, qty: 0 },
        ],
      },
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 3,
  },
  {
    display: "Dimensions",
    action: "edit_delete",
    editIsVisible: false,
    indexPosition: 3,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,
    structure: {
      left: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Inches", isSelected: false, price: 0, qty: 0 },
          { id: 1, name: "Centimeters", isSelected: false, price: 0, qty: 0 },
          { id: 2, name: "Other", isSelected: false, price: 0, qty: 0 },
        ],
      },
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 4,
  },
  {
    display: "Finish",
    action: "delete",
    indexPosition: 4,
    editIsVisible: false,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 5,
  },
  {
    display: "Material",
    action: "delete",
    indexPosition: 5,
    editIsVisible: false,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 9,
  },
  {
    display: "Pattern",
    action: "delete",
    indexPosition: 6,
    editIsVisible: false,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 10,
  },
  {
    display: "Scent",
    action: "delete",
    indexPosition: 7,
    editIsVisible: false,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 12,
  },
  {
    display: "Size",
    action: "edit_delete",
    editIsVisible: false,
    indexPosition: 8,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      left: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Baby Boys", isSelected: false, price: 0, qty: 0 },
          { id: 1, name: "Baby Girls", isSelected: false, price: 0, qty: 0 },
          { id: 2, name: "Boys", isSelected: false, price: 0, qty: 0 },
          { id: 3, name: "Babies", isSelected: false, price: 0, qty: 0 },
          { id: 4, name: "Children", isSelected: false, price: 0, qty: 0 },
          { id: 5, name: "Girls", isSelected: false, price: 0, qty: 0 },
          { id: 6, name: "Teen Girls", isSelected: false, price: 0, qty: 0 },
          { id: 7, name: "Teen Boys", isSelected: false, price: 0, qty: 0 },
          { id: 8, name: "Teens", isSelected: false, price: 0, qty: 0 },
          { id: 9, name: "Men", isSelected: false, price: 0, qty: 0 },
          { id: 10, name: "Women", isSelected: false, price: 0, qty: 0 },
          { id: 11, name: "Unisex Adults", isSelected: false, price: 0, qty: 0 },
          { id: 12, name: "Not specified", isSelected: false, price: 0, qty: 0 },
        ],
      },
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 13,
  },
  {
    display: "Style",
    action: "delete",
    indexPosition: 9,
    editIsVisible: false,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,

    structure: {
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 14,
  },
  {
    display: "Width",
    action: "edit_delete",
    editIsVisible: false,
    indexPosition: 10,
    isSelected: false,
    isCustom: false,
    price_vary: false,
    qty_vary: false,
    hasSaved: false,
    structure: {
      left: {
        top: "dropDownSelect",
        data: [
          { id: 0, name: "Inches", isSelected: false, price: 0, qty: 0 },
          { id: 1, name: "Centimeters", isSelected: false, price: 0, qty: 0 },
          { id: 2, name: "Other", isSelected: false, price: 0, qty: 0 },
        ],
      },
      right: {
        top: "inputText",
        inputValue: "",
        textComponentIsVisible: false,
        options: [],
        hasError: true,
      },
    },
    value: 15,
  },
];
