import { faCircle } from "@fortawesome/free-solid-svg-icons";


export const data = [
  {
    category: "Makeup Artist near you",
    makeUpArtist: [
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549989476-69a92fa57c36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549396535-c11d5c55b9df?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1550338861-b7cfeaf8ffd8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549737328-8b9f3252b927?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1550064824-8f993041ffd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
    ],
  },
  {
    category: "Hair stylist near you",
    makeUpArtist: [
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549989476-69a92fa57c36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549396535-c11d5c55b9df?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1550338861-b7cfeaf8ffd8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1549737328-8b9f3252b927?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
      {
        review: 5.0,
        totalReviews: "123 reviews",
        image: "https://images.unsplash.com/photo-1550064824-8f993041ffd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        businessName: "Business Name",
        distanceFrom: "1.1 mi",
        icon: faCircle,
        businessAddress: "1814 dylane drive Apt 2l, Griffith, indi...",
      },
    ],
  },
];
